### ISSUE TITLE
REPORTE ENTREVISTA

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-v-a-k#1]
[REPORTE DE LA ENTREVISTA FUNDAMENTOS ING. DE SOFTWARE.pdf](https://github.com/user-attachments/files/16830801/REPORTE.DE.LA.ENTREVISTA.FUNDAMENTOS.ING.DE.SOFTWARE.pdf)

**Comment by Diegocruz040708** [comment]
Según la rubrica Obtuvieron el 20% 
Cumplen con todos los criterios de evaluación

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
